enable puppet-lint checks

diff --git a/pre-receive b/pre-receive
--- a/pre-receive
+++ b/pre-receive
@@ -32,19 +32,24 @@ while read oldrev newrev refname; do
                     status=1
                 fi
                 # Check styleguide, but do not error if styleguide does not pass
-                # /usr/bin/puppet-lint --fail-on-warnings --no-80chars-check $tmpmodule > $tmperror
-                # rc=$?
-                # if [[ $rc != 0 ]]; then
-                #     if [[ $warned = 0 ]]; then
-                #         echo -e "${yellow}Please follow the puppet module styleguide (http://docs.puppetlabs.com/guides/style_guide.html).${reset}"
-                #         echo -e "${red}The following ERROR/WARNING messages are informational only. The commit has been accepted. In the future, these will cause your commit to be refused.${reset}"
-                #         warned=1
-                #     fi
-                #     echo -e "${yellow}Style guide compliance errors in $puppetmodule:${reset}"
-                #     echo -e "${yellow}"
-                #     cat $tmperror
-                #     echo -e "${reset}"
-                # fi
+                /usr/bin/puppet-lint \
+                    --fail-on-warnings \
+                    --no-80chars-check \
+                    --no-double_quoted_strings-check \
+                    --no-arrow_alignment-check \
+                    $tmpmodule > $tmperror
+                rc=$?
+                if [[ $rc != 0 ]]; then
+                    if [[ $warned = 0 ]]; then
+                        echo -e "${yellow}Please follow the puppet module styleguide (http://docs.puppetlabs.com/guides/style_guide.html).${reset}"
+                        echo -e "${red}The following ERROR/WARNING messages are informational only. The commit has been accepted. In the future, these will cause your commit to be refused.${reset}"
+                        warned=1
+                    fi
+                    echo -e "${yellow}Style guide compliance errors in ${green}$puppetmodule:${yellow}"
+                    echo
+                    cat $tmperror
+                    echo -e "${reset}"
+                fi
                 ;;
             *.erb )
                 cat $tmpmodule | erb -x -T - | ruby -c > /dev/null 2> $tmperror
