Fix to work
- output cleanup
- git diff from oldrev..newrev
- comment out puppet-lint, we don't have it yet
- parse all files so we know all files that failed

diff --git a/pre-receive b/pre-receive
--- a/pre-receive
+++ b/pre-receive
@@ -1,55 +1,65 @@
 #!/bin/bash
 
 warned=0
+status=0
+
+# colors
+cyan="\e[0;36m"
+red="\e[0;31m"
+yellow="\e[0;33m"
+green="\e[0;32m"
+reset="\e[0m"
 
 while read oldrev newrev refname; do
-    for puppetmodule in `git diff-tree --no-commit-id --name-only -r $newrev`; do
-        echo -e "\e[0;36m" "Checking $puppetmodule for syntax errors and styleguide compliance..." "\e[0m"
+    echo -e "${cyan}Checking $puppetmodule for syntax errors and styleguide compliance...${reset}"
+
+    for puppetmodule in `git diff-tree --no-commit-id --name-only -r $oldrev..$newrev`; do
         tmpdir=`mktemp -d`
         tmpmodule="$tmpdir/$puppetmodule"
         tmperror="$tmpdir/errors.txt"
         mkdir -p $tmpmodule
         rmdir $tmpmodule
+
         git show $newrev:$puppetmodule > $tmpmodule
         case $puppetmodule in
-            *.pp ) 
-                puppet parser validate $tmpmodule 2&> $tmperror
+            *.pp )
+                puppet parser validate $tmpmodule 2> $tmperror
                 rc=$?
-                if [[ $rc != 0 ]]; then
-                    echo -e "\e[0;31m'puppet parser validate' failed on $puppetmodule - push deniend. Run tests locally and confirm they pass before pushing. \e[0m"
+                if [[ $rc -ne 0 ]]; then
+                    echo -e "${red}'puppet parser validate' failed on '${green}$puppetmodule${red}' - push denied. Run tests locally and confirm they pass before pushing.${reset}"
                     cat $tmperror
-                    rm -rf $tmpdir
-                    exit $rc
+                    echo
+                    status=1
                 fi
                 # Check styleguide, but do not error if styleguide does not pass
-                /usr/bin/puppet-lint --fail-on-warnings --no-80chars-check $tmpmodule > $tmperror
-                rc=$?
-                if [[ $rc != 0 ]]; then
-                    if [[ $warned = 0 ]]; then
-                        echo -e "\e[0;31m" "Please follow the puppet module styleguide (http://docs.puppetlabs.com/guides/style_guide.html)." "\e[0m"
-                        echo -e "\e[0;31m" "The following ERROR/WARNING messages are informational only. The commit has been accepted. In the future, these will cause your commit to be refused." "\e[0m"
-                        warned=1
-                    fi
-                    echo -e "\e[0;33m" "Style guide compliance errors in $puppetmodule:" "\e[0m"
-                    echo -e "\e[0;33m"
-                    cat $tmperror
-                    echo -e "\e[0m"
-                fi
+                # /usr/bin/puppet-lint --fail-on-warnings --no-80chars-check $tmpmodule > $tmperror
+                # rc=$?
+                # if [[ $rc != 0 ]]; then
+                #     if [[ $warned = 0 ]]; then
+                #         echo -e "${yellow}Please follow the puppet module styleguide (http://docs.puppetlabs.com/guides/style_guide.html).${reset}"
+                #         echo -e "${red}The following ERROR/WARNING messages are informational only. The commit has been accepted. In the future, these will cause your commit to be refused.${reset}"
+                #         warned=1
+                #     fi
+                #     echo -e "${yellow}Style guide compliance errors in $puppetmodule:${reset}"
+                #     echo -e "${yellow}"
+                #     cat $tmperror
+                #     echo -e "${reset}"
+                # fi
                 ;;
             *.erb )
                 cat $tmpmodule | erb -x -T - | ruby -c > /dev/null 2> $tmperror
                 rc=$?
-                if [[ $rc != 0 ]]; then
-                    echo -e "\e[0;31m" "Ruby syntax checker failed on template $puppetmodule:" "\e[0m"
-                    echo -e "\e[0;33m"
+                if [[ $rc -ne 0 ]]; then
+                    echo -e "${red}Ruby syntax checker failed on template '${green}${puppetmodule}${yellow}':"
+                    echo
                     cat $tmperror
-                    echo -e "\e[0m"
-                    echo -e "\e[0;33m" "Commit accepted, but the above template will not expand properly" "\e[0m"
+                    echo -e "${reset}"
+                    status=1
                 fi
                 ;;
         esac
         rm -rf $tmpdir
     done
 done
-# Everything went OK so we can exit with a zero
-exit 0
+
+exit $status
